name: Always Fail Workflow

on: [pull_request]

jobs:
  always_fail:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deliberate Failure
        run: exit 1